FROM elastic/filebeat:8.15.0

USER root

RUN chmod go-w /usr/share/filebeat/filebeat.yml

CMD sh -c "echo 'INICIANDO Filebeat...'; filebeat -e -strict.perms=false  -d 'publish'"
# CMD sh -c "echo 'INICIANDO Filebeat...'; filebeat -e   -d 'publish'"