# version: '3.8'
services:
  kafka:
    build:
      context: .
      dockerfile: Dockerfile.kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KF_SERVER: --bootstrap-server kafka:9092
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 # esto genera el  __consumer_offsets de lo contraio da
      # KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      # KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      # KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  logstash:
    # image: docker.elastic.co/logstash/logstash:8.15.0
    build:
      context: .
      dockerfile: Dockerfile.logstash
    container_name: logstash
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash.yml:/usr/share/logstash/config/logstash.yml
    depends_on:
      - kafka
    ports:
      - "5044:5044"

    environment:
      ELASTIC_CONTAINER: false

  filebeat:
    # image: elastic/filebeat:8.15.0
    build:
      context: .
      dockerfile: Dockerfile.filebeat
    container_name: filebeat
    depends_on:
      - kafka
    volumes:
      - ./TODO1/:/usr/share/filebeat/TODO1/
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml