filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - C:\Users\romar\OneDrive\Desktop\prueba-tecnica\TODO1\*.json
    # json.keys_under_root: true
    # json.add_error_key: true

processors:
  - decode_json_fields:
      fields: ["message"]
      target: ""
  - drop_fields:
      fields: ["@timestamp", "log", "input", "ecs", "host", "agent"]
  - script:
      lang: javascript
      id: convert_to_csv
      source: >
        function process(event) {
          var data = event.Get("message");
          if (data) {
            try {
              var json = JSON.parse(data);
              var keys = Object.keys(json);
              var values = keys.map(function(key) {
                return json[key];
              });
              var csv = keys.join(";") + "\n" + values.join(";") + "\n";
              event.Put("message", csv);
            } catch (e) {
              event.Put("message", "Error converting JSON to CSV: " + e.message);
            }
          }
        }

output.kafka:

  hosts: ["localhost:9092"]
  topic: "todo1-topic"
  partition.round_robin:
    reachable_only: false
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000
  codec:
    format:
      string: "%{[message]}"
